### ISSUE TITLE
What about authentication?

### ISSUE THREAD

**Issue by DQvsRA** [cdaringe/pouchy#149]
Can i use pouchdb-authentication plugin?

**Comment by swashcap** [comment]
Pouchy [adds a PouchDB reference to itself](https://github.com/cdaringe/pouchy/blob/56a23c4298293fba6b7572ceb38473d1b3a02aaa/src/index.js#L620). You should be able to use that with [PouchDB’s plugin API](https://pouchdb.com/api.html#plugins):

```js
var Pouchy = require('pouchy')
var pouchDBAuthentication = require('pouchdb-authentication')

Pouchy.PouchDB.plugin(pouchDBAuthentication)
```

**Comment by cdaringe** [comment]
`plugin` is also a 1st class citizen:

https://github.com/cdaringe/pouchy/blob/56a23c4298293fba6b7572ceb38473d1b3a02aaa/src/index.js#L578

`Pouchy.plugin` also works.
