### ISSUE TITLE
Invalid Adapter: undefined

### ISSUE THREAD

**Issue by DQvsRA** [cdaringe/pouchy#150]
Hi

I have a problem with webpack

On client:

```
const Pouchy = require('pouchy');
const db = new Pouchy({
        name: 'users',
        replicate: 'sync',
        url: ServerDefinition.ADDRESS + Collections.USERS
    });
```

![screenshot from 2017-02-19 13 09 34](https://cloud.githubusercontent.com/assets/442111/23102198/1077ea54-f6a5-11e6-93d2-2d3812d6a857.png)

And this is my webpack config (part of)

```
const config = {
    entry:  {
        site      : APP_DIR + '/site/index.js',
        entrance  : APP_DIR + '/entrance/index.js',
        vendor    : [
            'pouchy',
            'pouchdb',
            'lodash'
        ]
    },
    output: {
        path: BUILD_DIR,
        filename: '[name].js'
    },
    resolve: {
        alias: {
            'vue$': 'vue/dist/vue.common.js'
            // semantic: path.resolve('./libs/semantic/dist/semantic.js')
        }
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor', // Specify the common bundle's name.
            filename: "vendors.bundle.js"
        }),
```

**Comment by swashcap** [comment]
My guess is that [the necessary adapters](https://github.com/cdaringe/pouchy/blob/56a23c4298293fba6b7572ceb38473d1b3a02aaa/package.json#L41-L42) aren’t making it into your bundle, so any `require`s aren’t able to resolve. Do you have a repo?

**Comment by cdaringe** [comment]
yea, that must be it.  we bake in the http adapter by default for when we use URLs, but we cannot reliably pick browser default adapters (memory/websql/indexeddb/etc).

also, we now do browser tests + node tests 🎉

**Comment by cdaringe** [comment]
closing for now but feel free to reopen or ask more questions

**Comment by avalanche1** [comment]
Isnt the indexedDB adapter supposed to be bundled in by default?
This is very confusing..

**Comment by cdaringe** [comment]
@avalanche1, no, just the http adapter.  The indexedb adapter would only work in browsers. 
 Feel free to send another issue or an example and Id be happy to look
