### ISSUE TITLE
Cannot resolve dependency 'pouchy'

### ISSUE THREAD

**Issue by avalanche1** [cdaringe/pouchy#277]
`import Pouchy from 'pouchy'`
Error: `Cannot resolve dependency 'pouchy'` when using parcel & typescript.
Happens on `"pouchy": "^13.0.3"`.
On `"pouchy": "^12.3.1"` all is fine.

**Comment by cdaringe** [comment]
thanks for the report.  that was embarrassing. 14.x is released now.  semantic-release is being a little finicky.  13/14.x are fully compatible--semantic-release wasn't picking up valid tags, so had to force a major.

**Comment by cdaringe** [comment]
parcel/typescript MVP: https://github.com/cdaringe/parcel-typescript
