### ISSUE TITLE
Docs: mention the steps needed to get indexedDB working

### ISSUE THREAD

**Issue by avalanche1** [cdaringe/pouchy#278]
Hi!
Continuing [this](https://github.com/cdaringe/pouchy/issues/150#issuecomment-542031381).
I personally came to PouchDB and then Pouchy because I needed an abstaction over IndexedDB api. 
In my understanding, PouchDB was initially created to provide this very api; and then it evolved into smth bigger. Maybe it's wrong understanding.
So.. it was only reasonable to expect Pouchy to work with IndexedDB out of the box. It took me quite some time to figure the adaptor stuff out, by also scanning through closed issues here.
Therefore, I would ask you to explicitly mention steps needed to get going with IndexedDB. In the Guide or Getting started section of the docs. Thx.

**Comment by cdaringe** [comment]
Ya, that's a fair callout. A short "getting started" section is probably worthwhile

**Comment by cdaringe** [comment]
Did you figure it out?  If not, the adapter stuff is the exact same as PouchDB, and the readme shows a few examples of plugging in PouchDB adapters

**Comment by avalanche1** [comment]
Yeah, I did. But there were still some issues that took too much time, I don't remember now exactly what, but they made me switch to Dexie.
